// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNrgnc-yT0eBqJlbwunWxfEkTalWwFfC8',
    appId: '1:82091958900:web:31ac70c43b7b51ffb9e721',
    messagingSenderId: '82091958900',
    projectId: 'agroforest-20335',
    authDomain: 'agroforest-20335.firebaseapp.com',
    storageBucket: 'agroforest-20335.firebasestorage.app',
    measurementId: 'G-Z844J3KMNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXIaCOx3p8VTlyLPMs4S6p0Tng1OETEdM',
    appId: '1:82091958900:android:6ba739af933151efb9e721',
    messagingSenderId: '82091958900',
    projectId: 'agroforest-20335',
    storageBucket: 'agroforest-20335.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdECMDMZmCPDnJWGw6aBEDQq4PhPBBnS4',
    appId: '1:82091958900:ios:6501065d1c42d7f7b9e721',
    messagingSenderId: '82091958900',
    projectId: 'agroforest-20335',
    storageBucket: 'agroforest-20335.firebasestorage.app',
    iosBundleId: '9',
  );
}
